# ######## Window rules ########

# Uncomment to apply global transparency to all windows:
windowrule {
	name = global-transparency
	match:class = .*
	opacity = 0.95
}

# Disable blur for XWayland windows (or context menus with shadow would look weird)
windowrule {
	name = xwayland
	match:class = xwayland
	no_blur = 1
}

windowrule {
	name = firefox-transparency
	match:class = firefox
	opacity = 1.0
}
windowrule {
	name = brave-transparency
	match:class = Brave-browser
	opacity = 1.0
}
windowrule {
	name = spotify-transparency
	match:class = spotify
	opacity = 1.0
}
windowrule {
	name = nautilus-transparency
	match:class = org.gnome.Nautilus
	opacity = 1.0
}
windowrule {
	name = better_control-transparency
	match:class = better_control.py
	opacity = 1.0
}
windowrule {
	name = network_manager-transparency
	match:class = com.network.manager
	opacity = 1.0
}
windowrule {
	name = pavucontrol-transparency
	match:class = org.pulseaudio.pavucontrol
	opacity = 1.0
}
windowrule {
	name = ape-transparency
	match:class = ape
	opacity = 1.0
}


# Floating
windowrule {
	name = ape-transparency
	match:class = ape
	opacity = 1.0
}



# ######## Workspace rules ########
workspace = special:special, gapsout:30

# ######## Layer rules ########
layerrule = xray 1, match:namespace .*
layerrule = no_anim 1, match:namespace walker
layerrule = no_anim 1, match:namespace selection
layerrule = no_anim 1, match:namespace overview
layerrule = no_anim 1, match:namespace anyrun
layerrule = no_anim 1, match:namespace indicator.*
layerrule = no_anim 1, match:namespace osk
layerrule = no_anim 1, match:namespace hyprpicker

